apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: gestion-absence
        image: aya452/imagee:latest
        ports:
        - containerPort: 80
        env:
        - name: APACHE_RUN_USER
          value: www-data
        - name: APACHE_RUN_GROUP
          value: www-data
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  selector:
    app: php-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
